### PR TITLE
top nav and profile page added #hacktoberfest

### PR DESCRIPTION
**Pull request by kamaldlk**
react-router-dom  added for routing 
screenshot 2018-10-21 at 5 36 15 pm

### CODE REVIEW

**Comment by vimark1** [comment]
hi @kamaldlk - Thank you for your contribution.  Are you still working on this or is it ready to be reviewed?

**Comment by kamaldlk** [comment]
i'm completed

**Comment by kamaldlk** [comment]
i'm completed

**Comment by vimark1** [comment]
ok thanks, I will review/merge this soon

**Pull request closed without merging**
