### PR TITLE
Enable enter button for login and register forms

### LINKED ISSUE #54: Enter key doesn't work from password field
When I enter a password, I expect to be able to hit the Enter key and begin the sign up or sign in process.  But typist requires a user to navigate to the button.

### PR DESCRIPTION
**Pull request by clayreimann**
* Also bind input handlers to prevent re-renders
* Create shared FormInput component

Closes #54 
Closes #68

### CODE REVIEW

**Comment by rahul1995** [comment]
@clayreimann @vimark1 why is onChange being called only when user hits enter key or clicks button? https://codepen.io/gaearon/pen/VmmPgp?editors=0010
Here onChange() is called on every keystroke in the input field. I am confused. Could any of you guys help?

**Comment by vimark1** [comment]
@rahul1995 the change here that makes it behave as expected when you hit enter, is wrapping the input fields in a HTML form. You are right though, `onChange` is called on every keystroke, it's a way to keep state updated.  When the user hits `enter` in the form, it triggers the `onSubmit` function.

**Comment by rahul1995** [comment]
@vimark1 sorry but I couldn't understand. we are passing `this.signup()` in 'onChange` but it is running only on pressing enter. On the other hand, in `onSubmit`, we are doing nothing but `e.preventDefault()` but that is validating inputs and submitting form.

**Comment by vimark1** [comment]
Ah yes, you’re right. Maybe it’s not working as intended. Have you tested it?

**Comment by rahul1995** [comment]
@vimark1 It's working completely fine. @clayreimann would you please explain why it's working?

**Pull request merged**
