### PR TITLE
Add basic Leaderboard

### PR DESCRIPTION
**Pull request by rahul1995**

### CODE REVIEW

**Comment by vimark1** [comment]
@rahul1995 I can't get this to work.  Can you check it's working for you?  The issue is that when I complete the sessions nothing gets saved.  Thanks

**Comment by rahul1995** [comment]
@vimark1 I was getting permission denied error to write into database, I don't know how to test it? Is it possible for you to give access on certain node of firebase? I am new to firebase actually.

**Comment by vimark1** [comment]
@rahul1995 ah ok, true, you'll need to edit the rules.json file. See https://firebase.google.com/docs/database/security/

For now I will add read and write for all users in `top-scorers` which should resolve the issue

**Comment by vimark1** [comment]
@rahul1995 I've made some changes, are you still getting a write error in development?

**Comment by vimark1** [comment]
It is working for me now

**Comment by vimark1** [comment]
The table is just in reverse order, see https://deploy-preview-67--typistapp.netlify.com/scoreboard

**Comment by rahul1995** [comment]
Oh yes, table is gonna be in reverse order. lemme just change the compare function inside sort. 🤣

**Comment by rahul1995** [comment]
@vimark1 fixed the sorting order

**Pull request merged**
